# Copyright (c) Blecon Ltd
# SPDX-License-Identifier: Apache-2.0
manifest:
  projects:
    - name: nrf
      revision: v2.8.0
      url: http://github.com/nrfconnect/sdk-nrf
      import:
        path-blocklist:
          - nrf/modules/memfault-firmware-sdk/*
    - name: zephyr
      revision: v3.7.99-ncs1
      url: https://github.com/nrfconnect/sdk-zephyr
      import:
        name-allowlist:
          - TraceRecorderSource
          - canopennode
          - chre
          - cmsis
          - cmsis-dsp
          - cmsis-nn
          - edtt
          - fatfs
          - hal_nordic
          - hal_st # required for ST sensors (unrelated to STM32 MCUs)
          - hal_wurthelektronik
          - liblc3
          - libmetal
          - littlefs
          - loramac-node
          - lvgl
          - lz4
          - mipi-sys-t
          - nanopb
          - net-tools
          - nrf_hw_models
          - open-amp
          - picolibc
          - segger
          - tinycrypt
          - tf-m-tests
          - uoscore-uedhoc
          - zcbor
          - zscilib
    - name: blecon-device-sdk
      revision: fef8aba3d6f87bd613e0255030d8242380299919
      url: https://github.com/blecon/blecon-device-sdk
    - name: memfault-firmware-sdk
      revision: 1.12.0
      path: modules/lib/memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
  self:
    path: blecon-oem-device-firmware
