# Copyright (c) Blecon Ltd
# SPDX-License-Identifier: Apache-2.0

name: 'Get current version'
outputs:
  version:
    description: 'The current software version'
runs:
  using: 'docker'
  image: '../../../.devcontainer/Dockerfile'
  entrypoint: './blecon-zephyr-apps/.github/actions/action-get-version/entrypoint.sh'