# Copyright (c) Blecon Ltd
# SPDX-License-Identifier: Apache-2.0
name: release
on:
  workflow_dispatch: {}
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app: sensor-memfault
            board: kkm_s5_bcn
            variant: metrics
          - app: sensor-memfault
            board: kkm_s5_bcn
            variant: metrics-crashy-shake
          - app: sensor-default
            board: kkm_s5_bcn
          - app: sensor-default
            board: mkbnl02sn
            board_qualifiers: nrf54l15/cpuapp
          - app: proximity-spotter
            board: mkbnl02sn
            board_qualifiers: nrf54l15/cpuapp
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: blecon-oem-device-firmware
          fetch-tags: true
      - id: build
        name: Build app
        uses: ./blecon-oem-device-firmware/.github/actions/action-build-app
        with:
          app: ${{ matrix.app }}
          board: ${{ matrix.board }}
          board_qualifiers: ${{ matrix.board_qualifiers }}
          build_number: ${{ github.run_number }}
          variant: ${{ matrix.variant }}
          release: true
      - name: Archive Zephyr binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.variant && format('{0}-{2}-{1}', matrix.app, matrix.board, matrix.variant) || format('{0}-{1}', matrix.app, matrix.board) }}
          path: |
            ${{ steps.build.outputs.archive }}
          retention-days: ${{ github.ref == 'refs/heads/main' && 3 || 1 }} # Only archive build output from main branch
  Release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: blecon-oem-device-firmware
      - name: Erase previous artifacts
        run: rm -rf release-artifacts
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
      - name: Read version number
        id: read_version
        run: |
          version=$(cat blecon-oem-device-firmware/VERSION)
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          tag_name: v${{ steps.read_version.outputs.version }}
          generate_release_notes: true
          files: |
            release-artifacts/**/*.tar.bz2
