# Copyright (c) Blecon Ltd
# SPDX-License-Identifier: Apache-2.0

name: 'Build Zephyr firmware'
inputs:
  app:
    description: 'App to build'
    required: true
  board:
    description: 'Board to build for'
    required: true
  board_qualifiers:
    description: 'Board qualifiers'
    required: false
    default: ''
  build_number:
    description: 'Build number'
    required: false
    default: 0
  variant:
    description: 'Application variant'
    required: false
    default: ''
  release:
    description: 'Is a release build'
    required: false
    default: false
outputs:
  archive:
    description: 'The name of the archive containing the build artifacts'
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: './blecon-oem-device-firmware/.github/actions/action-build-app/entrypoint.sh'
  args:
    - ${{ inputs.app }}
    - ${{ inputs.board }}
    - ${{ inputs.board_qualifiers }}
    - ${{ inputs.build_number }}
    - ${{ inputs.release }}
    - ${{ inputs.variant }}
